neon_profile:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('NEON_HOST') }}"
      user: "{{ env_var('NEON_USER') }}"
      password: "{{ env_var('NEON_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('NEON_DB') }}"
      schema: "money_diaries"  # or specify your schema
      sslmode: "require"
  target: dev