version: 2

sources:
  - name: core
    schema: money_diaries

models:
  - name: reporting_blog_content_metrics
    description: the source of truth table for reporting purposes, all other views references this table
